// <auto-generated />
namespace Connect2Us3._01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    [GeneratedCode("EntityFramework", "6.4.4")]
    public sealed partial class AddBookRentalFields : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "20240930083000_AddBookRentalFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}